<div class="container">
    <div class="page-header">
        <h2>Wyniki dla Facebook'a</h2>
    </div>
    <div class="row">
        <div class='span12'>
            <?php if (isset($this->FB) && count($this->FB) > 0): ?>
                <table class=" table table-striped table-hover">
                    <thead>            
                        <tr>
                            <td>Zdjęcie</td>
                            <td>Imię i nazwisko</td>
                            <td>Opis</td>
                            <td>LINK do strony na FB</td>
                            <td>Wyszukiwanie</td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->FB as $value): ?>
                            <tr>
                                <td><?php echo $value['photo']; ?></td>
                                <td><?php echo $value['name']; ?></td>
                                <td><?php echo $value['desc']; ?></td>
                                <td><a href="<?php echo $value['link']; ?>">Strona na Facebook</td>
                                <td><a href="<?php echo $this->baseUrl() . '/index/fb-details?url=' . $value['link']; ?>" class="btn btn-link ajax-test">Więcej danych</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <ul class="pager">
                    <li class="previous <?php if ($this->Page == 0) echo 'disabled'; ?>"><a href="<?php echo $this->baseUrl() . '/index/facebook?name=' . $this->Name . '&page=' . ($this->Page - 1); ?>">← Poprzednia</a></li>
                    <li class="next"><a href="<?php echo $this->baseUrl() . '/index/facebook?name=' . $this->Name . '&page=' . ($this->Page + 1); ?>">Następna →</a></li>
                </ul>
            <?php else: ?>
                <h2>Brak wyników!</h2>
                <ul class="pager">
                    <li class="previous <?php if ($this->Page == 0) echo 'disabled'; ?>"><a href="<?php echo $this->baseUrl() . '/index/facebook?name=' . $this->Name . '&page=' . ($this->Page - 1); ?>">← Poprzednia</a></li>
                </ul>
            <?php endif; ?>
        </div>
    </div>
</div>
