<div class="container">
    <div class="page-header">
        <h1 id="name"><?php echo $this->Results['name']; ?></h1>
    </div>
    <div class="row">

        <div class="span6">
            <div id="image-container" style='text-align:center;'>
                <a style="display:none;" id="fb-photo-link"><?php echo $this->Results['link']; ?></a>
                <img src="<?php echo $this->baseUrl("img/loading.gif"); ?>" alt="Loading..." >
            </div>
            <?php if (isset($this->Results['bio']['desc'])): ?>
                <blockquote>
                    <?php echo $this->Results['bio']['desc']; ?>
                </blockquote>
            <?php endif; ?>
        </div>
        <div class="span6">
            <h2>Profil</h2>
            <table class="table table-striped table-hover">
                <tbody>
                    <tr>
                        <th><h4>Podstawowe informacje</h4></th>
                <td></td>
                </tr>
                <?php foreach ($this->Results['basics'] as $key => $res): ?>
                    <tr>
                        <td><?php echo $key; ?></td>
                        <td><?php echo $res; ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <th><h4>Kontakt</h4></th>
                <td></td>
                </tr>
                <?php foreach ($this->Results['contact'] as $key => $res): ?>
                    <tr>
                        <td><?php echo $key; ?></td>
                        <td><?php echo $res; ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <th><h4>Zamieszkanie</h4></th>
                <td></td>
                </tr>
                <?php foreach ($this->Results['living'] as $key => $res): ?>
                    <tr>
                        <td><?php echo $key; ?></td>
                        <td><?php echo $res; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <hr class="footer-divider"/>
    <?php if (count($this->Results['schools']) > 0): ?>
        <div class="row">
            <div class="span6">
                <h2>Wykształcenie</h2>
            </div>
            <div class="span12">
                <table  class="table table-striped table-hover">
                    <thead>            
                        <tr>
                            <td><strong>Szkoła</strong></td>
                            <td><strong>Opis</strong></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->Results['schools'] as $res): ?>
                            <tr>
                                <td><p><?php echo $res['name']; ?></p></td>
                                <td>
                                    <?php
                                    foreach ($res['desc'] as $value) {
                                        echo "<p>";
                                        print_r($value);
                                        echo "</p>";
                                    }
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif; ?>
    <?php if (count($this->Results['jobs']) > 0): ?>
        <div class="row">
            <div class="span6">
                <h2>Praca</h2>
            </div>
            <div class="span12">
                <table  class="table table-striped table-hover">
                    <thead>            
                        <tr>
                            <td><strong>Praca</strong></td>
                            <td><strong>Opis</strong></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->Results['jobs'] as $res): ?>
                            <tr>
                                <td><p><?php echo $res['name']; ?></p></td>
                                <td>
                                    <?php
                                    foreach ($res['desc'] as $value) {
                                        echo "<p>";
                                        print_r($value);
                                        echo "</p>";
                                    }
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif; ?>
    <hr class="footer-divider"/>
    <div class="row">
        <div class="span6">
            <h2>Wyniki z google</h2>
        </div>
        <div class="span6">
            <h2>Rodzina</h2>
        </div>
        <div id="googleResults" class="span6">
            <img src="<?php echo $this->baseUrl("img/loading.gif"); ?>" alt="Loading...">
            <a href="<?php echo $this->url(array('controller' => "index", "action" => "google")); ?>" class="btn btn-link google-search">Szukaj w google</a>
        </div>
        <div class="span6">
            <?php if (count($this->Results['family']) > 0): ?>
                <div class='row'>
                    <?php foreach ($this->Results['family'] as $member): ?>
                        <div class='span3'>
                            <div class='well'>
                                <p><?php echo $member['relation']; ?></p>
                                <?php echo $member['photo']; ?>
                                <h3><?php echo $member['name']; ?></h3>
                                <a href="<?php echo $member['link']; ?>">Idź do strony na Facebook'u</a>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php else: ?>
                <h2>Brak wyników</h2>
            <?php endif; ?>
        </div>
        <div class="span6">
            <h2>Tagi ze zdjęcia</h2>
            <div id="tagResults">
                <img src="<?php echo $this->baseUrl("img/loading.gif"); ?>" alt="Loading...">
            </div>
        </div>
    </div>
</div>