<div class="container">
    <div class="page-header">
        <h2>Wyszukiwarka z nk.pl</h2>
    </div>
    <div class="row">
        <form class="span12" action="<?php echo $this->baseUrl() . '/naszaklasa/index/'; ?>" method="GET">
            <label>Wpisz poszukiwanego człowieka:</label>
            <input type="text" name="name" class="input-large search-query"/>
            <input type="submit" class="btn btn-primary" value="Szukaj"/>
        </form>
    </div>
    <div class="page-header">
        <h2>Wyszukiwarka z Facebook'a</h2>
    </div>
    <div class="row">
        <form class="span12" action="<?php echo $this->baseUrl() . '/facebook/index/'; ?>" method="GET">
            <label>Wpisz poszukiwanego człowieka:</label>
            <input type="text" name="name" class="input-large search-query"/>
            <input type="submit" class="btn btn-primary" value="Szukaj"/>
        </form>
    </div>
    <div class="page-header">
        <h2>Analizator tagów obrazów</h2>
    </div>
    <div class="row">
        <form class="span12" action="<?php echo $this->baseUrl() . '/index/photo-info/'; ?>" method="GET">
            <label>Wpisz adres obrazu do zbadania:</label>
            <input type="text" name="url" class="input-large search-query"/>
            <input type="submit" class="btn btn-primary" value="Badaj"/>
        </form>
    </div>
</div>