<div class="container">
    <div class="page-header">
        <h2>Wyszukiwarka</h2>
    </div>
    <div class="row-fluid">
        <form class="span12" action="<?php echo $this->baseUrl() . '/index/facebook/'; ?>" method="GET">
            <label>Wpisz poszukiwanego człowieka</label>
            <input type="text" name="name"/>
            <input type="submit" class="btn btn-primary" value="Szukaj"/>
        </form>
    </div>
</div>