<div class="container">
    <div class="page-header">
        <h2>Wyszukiwarka</h2>
    </div>
    <div class="row-fluid">
        <form class="span12" action="<?php echo $this->baseUrl() . '/index/facebook/'; ?>" method="GET">
            <label>Wpisz poszukiwanego człowieka (facebook):</label>
            <input type="text" name="name" class="input-large search-query"/>
            <input type="submit" class="btn btn-primary" value="Szukaj"/>
        </form>
    </div>
    <div class="row-fluid">
        <form class="span12" action="<?php echo $this->baseUrl() . '/index/nk/'; ?>" method="GET">
            <label>Wpisz poszukiwanego człowieka (nasza-klasa):</label>
            <input type="text" name="name" class="input-large search-query"/>
            <input type="submit" class="btn btn-primary" value="Szukaj"/>
        </form>
    </div>
    <!--<a href="<?php echo $this->url(array('controller' => "index", "action" => "nk")); ?>" class="btn btn-link nk-test">Więcej danych</a>-->
    
</div>