<div class="container">
    <div class="page-header">
        <h2>Wyniki dla nk.pl</h2>
    </div>
    <div class="row">
        <table  class=" table span12 table-striped table-hover">
            <thead>            
                <tr>
                    <td>Zdjęcie</td>
                    <td>Imię i nazwisko</td>
                    <td>Miasto</td>
                    <td>Wyszukiwanie</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->Results as $res): ?>
                    <tr>
                        <td><?php echo $res[0]; ?></td>
                        <td><?php echo strip_tags($res[1]); ?></td>
                        <td><?php echo $res[3]; ?></td>
                        <td><a href="<?php echo $this->url(array("controller" => "index", "action" => "details"))."?link=" . $res[2];?>" class="btn btn-link">Więcej danych</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>