<div class="container">
    <div class="page-header">
        <h1>Szczegółowe tagi zdjęcia:</h1>
    </div>
    <div class="row">
        <div class="span12">
            <div class="well" style="text-align: center; ">
                <img src="<?php echo $this->Url; ?>" alt="image" />  
            </div>
        </div>
    </div>
    <div>
        <hr class="footer-divider"/>
        <div class=" offset1 span10">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <td><strong>Właściwość</strong></td>
                        <td><strong>Wartość</strong></td>
                    </tr>
                </thead>
                <?php foreach ($this->Results as $key => $value): ?>
                    <tr>
                        <td><?php echo $key; ?></td>
                        <td>
                            <?php
                            if (is_array($value)) {
                                echo "<pre>";
                                print_r($value);
                                echo "</pre>";
                            }
                            else
                                echo $value;
                            ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

    </div>