<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Projekt technologie internetowe 2013">
        <meta name="author" content="Radosław Przebieglec | Szymon Ząbkiewicz">
        <title>WebDetective - Projekt AiR 2013 TI</title>

        <?php
        $this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.min.css"))
                ->appendStylesheet($this->baseUrl("css/bootstrap-responsive.min.css"))
                ->appendStylesheet($this->baseUrl("css/font-awesome.css"))
                ->appendStylesheet($this->baseUrl("css/font-awesome-ie7.css"))
                ->appendStylesheet($this->baseUrl("css/boot-business.css"))
                ;
        echo $this->headLink();
        ?>
    </head>
    <body>
        <!-- Start: HEADER -->
        <header>
            <!-- Start: Navigation wrapper -->
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a href="<?php echo $this->baseUrl();?>" class="brand brand-bootbus">WebDetective</a>
                    </div>
                </div>
            </div>
            <!-- End: Navigation wrapper -->   
        </header>
        <!-- End: HEADER -->
        <!-- Start: MAIN CONTENT -->
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <!-- End: MAIN CONTENT -->
        <!-- Start: FOOTER -->
        <footer>
            <div class="container">
                <div class="row">
                </div>
            </div>
            <hr class="footer-divider"/>
            <div class="container">
                <p>
                    &copy; 2013 - Radosław Przebieglec & Szymon Ząbkiewicz, All Rights Reserved.
                </p>
            </div>
        </footer>
        <!-- End: FOOTER -->
        <?php
        $this->headScript()->appendFile($this->baseUrl("js/jquery.min.js"))
                ->appendFile($this->baseUrl("js/bootstrap.min.js"))
                ->appendFile($this->baseUrl("js/boot-business.js"))
                ->appendFile($this->baseUrl("js/detailsDownloader.js"));
        echo $this->headScript();
        ?>
    </body>
</html>