<div class="container">
    <div class="page-header">
        <h1 id="name"><?php echo $this->Results['data'][0][1] . " " . $this->Results['data'][2][1]; ?></h1>
    </div>
    <div class="row">
        <div class="span6">
            <div id="image-container">
                <?php echo $this->Results['photo']; ?>
            </div>
        </div>
        <div class="span6">
            <h2>Profil</h2>
            <table class="table table-striped table-hover">
                <tbody>
                    <tr>
                        <td>Profil na nk.pl</td>
                        <td><a href="<?php echo $this->WebSite; ?>" ><?php echo $this->Results['data'][0][1] . " " . $this->Results['data'][2][1]; ?></a></td>
                    </tr>
                    <?php foreach ($this->Results['data'] as $res): ?>
                        <tr>
                            <td><?php echo $res[0]; ?></td>
                            <td><?php echo $res[1]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <hr class="footer-divider"/>
    <div class="row">
        <div class="span6">
            <h2>Uczęszczane szkoly</h2>
        </div>
        <div class="span12">
            <table  class="table table-striped table-hover">
                <thead>            
                    <tr>
                        <td><strong>Szkoła</strong></td>
                        <td><strong>Klasa</strong></td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->Results['schools'] as $res): ?>
                        <tr>
                            <td><p><?php echo $res['school']; ?></p></td>
                            <td>
                                <?php
                                foreach ($res['classes'] as $value) {
                                    echo "<p>";
                                    print_r($value);
                                    echo "</p>";
                                }
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        
    </div>
    <hr class="footer-divider"/>
    <div class="row">
        <div class="span6">
            <h2>Wyniki z google</h2>
        </div>
        <div class="span6">
            <h2>Tagi ze zdjęcia</h2>
        </div>
        <div id="googleResults" class="span6">
            <img src="<?php echo $this->baseUrl("img/loading.gif"); ?>" alt="Loading...">
<!--<a href="<?php echo $this->url(array('controller' => "index", "action" => "google")); ?>" class="btn btn-link google-search">Szukaj w google</a>-->
        </div>
        <!--        <div class="span6">
                    <div class="alert-error">Tu będą wyniki z KRS</div><br/>
                    <a href="<?php echo $this->url(array('controller' => "index", "action" => "krs-details")); ?>" class="btn btn-link krs-ajax">Szukaj w KRS</a>
                    <input type="text" name="captcha" id="captcha"/>
                    <div id="krsResults">
                    </div>
                </div>-->
        <div class="span6">
            <div id="tagResults">
                <img src="<?php echo $this->baseUrl("img/loading.gif"); ?>" alt="Loading...">
            </div>
        </div>
    </div>
</div>